### ISSUE TITLE
No response frome button view reminders

### ISSUE THREAD

**Issue by tgly307** [scottleedavis/mattermost-plugin-remind#100]
I install v0.2.5 in MM v5.10, when I add a remind, the view reminders button in post message has no response. The issue is similar with #93 
![image](https://user-images.githubusercontent.com/25153311/57821806-79118f00-77c4-11e9-8836-1b51a7b5304c.png)
But there is no error log with this plugin

**Comment by scottleedavis** [comment]
Confirmed, thank you @tgly307 !  I will get to this asap.  :)

**Comment by scottleedavis** [comment]
@tgly307 the problem should be fixed in 0.2.6
https://github.com/scottleedavis/mattermost-plugin-remind/releases/tag/v0.2.6

**Comment by tgly307** [comment]
@scottleedavis thanks a lot!
I have test v0.2.6 on MM 5.11, it works fine.
I will close this issue.
