### ISSUE TITLE
plugin crash after any command

### ISSUE THREAD

**Issue by savauln** [scottleedavis/mattermost-plugin-remind#101]
I have crash reminder-plugin after send any command
`
{"level":"info","ts":1558205030.1905644,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:43:50 RPC call to LogError API failed: gob: gob: cannot encode nil pointer of type *model.AppError inside interface","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"info","ts":1558205030.192845,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:43:50 RPC call to SendEphemeralPost API failed: unexpected EOF","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"info","ts":1558205030.8294656,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:43:50 RPC call to KVGet API failed: connection is shut down","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"info","ts":1558205031.8297944,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:43:51 RPC call to KVGet API failed: connection is shut down","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"info","ts":1558205032.8302228,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:43:52 RPC call to KVGet API failed: connection is shut down","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"info","ts":1558205033.8302839,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:43:53 RPC call to KVGet API failed: connection is shut down","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"info","ts":1558205034.8305354,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:43:54 RPC call to KVGet API failed: connection is shut down","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"info","ts":1558205035.8310099,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:43:55 RPC call to KVGet API failed: connection is shut down","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"info","ts":1558205036.8312037,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:43:56 RPC call to KVGet API failed: connection is shut down","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"info","ts":1558205037.8315485,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:43:57 RPC call to KVGet API failed: connection is shut down","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"info","ts":1558205038.8316796,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:43:58 RPC call to KVGet API failed: connection is shut down","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"info","ts":1558205039.8655605,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:43:59 RPC call to KVGet API failed: connection is shut down","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"info","ts":1558205040.8346124,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:44:00 RPC call to KVGet API failed: connection is shut down","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"info","ts":1558205041.8348145,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:44:01 RPC call to KVGet API failed: connection is shut down","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"info","ts":1558205042.834924,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:44:02 RPC call to KVGet API failed: connection is shut down","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"info","ts":1558205043.8353271,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:44:03 RPC call to KVGet API failed: connection is shut down","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"info","ts":1558205044.8356488,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:44:04 RPC call to KVGet API failed: connection is shut down","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"info","ts":1558205045.8358645,"caller":"go-plugin/stream.go:15","msg":"2019/05/18 18:44:05 RPC call to KVGet API failed: connection is shut down","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","source":"plugin_stderr"}
{"level":"error","ts":1558205045.9894102,"caller":"mlog/log.go:172","msg":"RPC call ExecuteCommand to plugin failed.","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","error":"unexpected EOF"}
`

**Comment by scottleedavis** [comment]
@savauln what version of mattermost are you running and the host operating system (or if it is mattermost-docker)?

**Comment by savauln** [comment]
5.11.0 and i use official docker image mattermost/mattermost-team-edition

**Comment by scottleedavis** [comment]
Do these commands work (after uninstall/reinstall/reactivate), without any other commands?  What does the following return if so?
`/remind __user`

**Comment by scottleedavis** [comment]
Also, is the `siteURL` set?

**Comment by savauln** [comment]
"SiteURL": "https://mattermost.webpower.ru"

/remind __user
```
locale: en
location: UTC
```

**Comment by scottleedavis** [comment]
I appologize @savauln , I have been having issues getting 5.11.0 mattermost/mattermost-team-edition docker image running successfully.  I am used to the mattermost/mattermost-docker docker-compose approach, or the Docker Preview Image approach.  Perhaps you could help me get the equivalent running locally so I can reproduce the error?

Here is what I am getting after `docker run --name mattermost-team-edition -d --publish 8065:8065 --add-host dockerhost:127.0.0.1 mattermost/mattermost-team-edition:5.11.0`

```
{"level":"info","ts":1558402896.2234545,"caller":"app/server_app_adapters.go:58","msg":"Server is initializing..."}
{"level":"info","ts":1558402896.2285967,"caller":"sqlstore/supplier.go:224","msg":"Pinging SQL master database"}
{"level":"error","ts":1558402896.229329,"caller":"sqlstore/supplier.go:236","msg":"Failed to ping DB retrying in 10 seconds err=dial tcp 127.0.0.1:3306: connect: connection refused"}
{"level":"info","ts":1558402906.2300446,"caller":"sqlstore/supplier.go:224","msg":"Pinging SQL master database"}
{"level":"error","ts":1558402906.2308095,"caller":"sqlstore/supplier.go:236","msg":"Failed to ping DB retrying in 10 seconds err=dial tcp 127.0.0.1:3306: connect: connection refused"}
{"level":"info","ts":1558402916.2356954,"caller":"sqlstore/supplier.go:224","msg":"Pinging SQL master database"}
{"level":"error","ts":1558402916.2363472,"caller":"sqlstore/supplier.go:236","msg":"Failed to ping DB retrying in 10 seconds err=dial tcp 127.0.0.1:3306: connect: connection refused"}
```

**Comment by scottleedavis** [comment]
I am running a database with matching password at 3306

**Comment by scottleedavis** [comment]
@savauln I was able to get the mattermost-team-edition container to connect to a db at 3306, but I couldn't reach it via localhost:8065 using this:

`docker run --name mattermost-team-edition -d --publish 8065:8065 --network="host" mattermost/mattermost-team-edition:5.11.0`

I couldn't find setup usage for mattermost-team-edition, is the run command/setup something you could share?
https://docs.mattermost.com/install/docker-local-machine.html

**Comment by scottleedavis** [comment]
@savauln I was able to get the container mattermost/mattermost-team-edition running, though I wasn't able to replicate your issue.   (No problem in upload remind plugin, and run/interact with it)

Are there changes you have made to config/config.json beyond siteURL, sqlsettings->datasource and pluginsetting->enableuploads?  I am curious what would be different enough to break things.

**Comment by scottleedavis** [comment]
Do any other plugins work?
https://github.com/scottleedavis/mattermost-plugin-spybot ?
https://github.com/scottleedavis/mattermost-plugin-bot-test ?

**Comment by scottleedavis** [comment]
Have you tried disabling and enabling the plugin?

**Comment by scottleedavis** [comment]
Closing do to inactivity.  Can reopen/revisit if needed.
