### ISSUE TITLE
Would it be possible to add a "weekday" specifier

### ISSUE THREAD

**Issue by rosskusler** [scottleedavis/mattermost-plugin-remind#107]
Is it possible to specify something like, '/remind me to join the morning meeting every weekday at 8:30 am' ?  It doesn't accept weekday or monday-friday.  Do I have to set five separate reminders for each of Monday/Tuesday/Wednesday/Thursday/Friday?

**Comment by scottleedavis** [comment]
@rosskusler great point about weekdays.
This currently works "/remind me test every Monday,Tuesday,Wednesday,Thursday,Friday"
However a weekday keyword would be nicer.  Adding this as a todo.

**Comment by rosskusler** [comment]
Ahh... ok I see how that works.  Thank you @scottleedavis !!

**Comment by scottleedavis** [comment]
@rosskusler Added in release 0.3.0 https://github.com/scottleedavis/mattermost-plugin-remind/releases/tag/v0.3.0

`/remind me head home every weekday at 5pm`

Please file any issues you find!
