### ISSUE TITLE
Issues with Android app

### ISSUE THREAD

**Issue by poVoq** [scottleedavis/mattermost-plugin-remind#112]
Not quite sure how to explain, as there are various issues, but it does not seem to work as intended with the Mattermost Android app.

The overall responses are very sluggish and the buttons don't seem to work most of the time etc.
I does appear to work in general though, so sorry for this not very precise bug report.

Maybe this is a general issue with the mobile app and plugins?

But thanks a lot for working on this very useful plugin!

I am using Mattermost 5.11 and the latest version of the app from the playstore.

**Comment by scottleedavis** [comment]
Hi @poVoq , it is a known issue with the current mobile app (android and ios) that most of the buttons in remind will not function.
https://github.com/mattermost/mattermost-mobile/issues/2807
https://mattermost.atlassian.net/browse/MM-15084

I believe the fix will be in by the next release (1.20 i think), or before or around June 16th.

As far as lag goes in interaction, I have occasionally experienced that as well in my phone (ios) and haven't dialed down to figure out what might be the cause.

**Comment by poVoq** [comment]
OK lets wait for the client update then. I'll close this when confirmed working.

**Comment by scottleedavis** [comment]
@poVoq it looks like the fix is scheduled for 1.21 in July instead.  https://mattermost.atlassian.net/plugins/servlet/mobile?originPath=%2Fbrowse%2FMM-15084#issue/MM-15084

**Comment by scottleedavis** [comment]
was looking forward to release today/tomorrow, but looks like the fix is pushed/updated in 1.22 planned release in august now.

**Comment by scottleedavis** [comment]
the issue looks resolved @poVoq , so hoping for mid august resolution

**Comment by poVoq** [comment]
seems to work now.
