### ISSUE TITLE
Reminder "in X" works fine but displayes "tomorrow"

### ISSUE THREAD

**Issue by zvukoper** [scottleedavis/mattermost-plugin-remind#114]
Small text display bug?

1. Set reminder /remind me "test" in 10 seconds.
2. Bot says it will be triggered tomorrow.
3. It triggers just fine in time and today.

![image](https://user-images.githubusercontent.com/511118/58680757-a47aa900-8382-11e9-8fc7-7d6ee0a42b6f.png)

**Comment by scottleedavis** [comment]
@zvukoper are you using v0.3.1?  T that version vs. 0.3.0

I believe this got fixed in 0.3.1 (didnt have this issue locally), are you using that version?

**Comment by zvukoper** [comment]
Sorry, I've missed that release. I've seen the new release 3 days ago, installed it and you've fired 0.3.1 just after that. Downloading it now and installing. I'l llet you know in a minute.

**Comment by zvukoper** [comment]
Yep! It is fixed. Thanks!
