### ISSUE TITLE
Include link in reminder to the conversation where i type "/remind me 2h"

### ISSUE THREAD

**Issue by abergs** [scottleedavis/mattermost-plugin-remind#116]
My use case is that:

when I'm in the middle of something and a team member asks me "Can you schedule a meeting to do this?". (This being something we have been discussing in the channel)

I would like to type /remind me 2h.

I would then like the reminder to be
"You asked me to remind you of [this](link-to-message)".

where link-to-message is the permalink to the message before i wrote "/remind me 2h"

**Comment by scottleedavis** [comment]
@abergs would this use case cover your request?  https://github.com/scottleedavis/mattermost-plugin-remind/issues/73

This should be working by release 5.13 I believe.

**Comment by abergs** [comment]
If in anyway it would be possible to make a written one that'd be even better because that'd be most intuitive. Would it be possible with the current API's of mattermost?

The example of this working quite well is actually how reddit reminders work, where you just comment with "!remindme 12h".

**Comment by scottleedavis** [comment]
@abergs I am trying to stay close to the slackbot `/remind` syntax.  There was a recent request for omited target defaults to 'me' https://github.com/scottleedavis/mattermost-plugin-remind/issues/118 s, and since slackbot does that it sounds fine.  

I am a little hesitant to add this behavior in the written/typed way beyond what https://github.com/scottleedavis/mattermost-plugin-remind/issues/73 will do, though not 100% opposed.

**Comment by abergs** [comment]
I am 👍 for the defaults to me and staying close to the slack implementation.

Regarding reminding about a message, if it shouldn't be a included by default, perhaps including a small token (`^`) to the message could trigger the link to be included.

E.g. `/remind me ^ 1h` or `/remind me "Check this^ before deploying to prod` 1h`.

Worst case I get a reminder with my text and a extra link to "when/where" i typed the reminder. So the downside doesn't really feel too bad.

**Comment by scottleedavis** [comment]
@abergs I think the idea is pretty neat, though I am still on the fence about implementation.  One could accomplish the same thing with copying the post permalink, and creating markdown, e.g.
`/remind me "check [this](permalink) before deploying to prod" 1h`

On one hand I want to make remind have useful features, and the other I would like it to stay as simple as the original design slack made.
