### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by getrich20** [scottleedavis/mattermost-plugin-remind#122]
I know this is the wrong place to post this but can I please have some help installing this on my local mattermost instance. Is there any good guide I can use? I downloaded the tar and uploaded it to the plugin section, installed go 1.12 and dep but still unable to use the plugin :(

**Comment by scottleedavis** [comment]
Sure thing @getrich20.  It sounds like you have mattermost running locally, is the SiteURL configured in the configuration section of the system console?  Is the plugin enabled?  What errors are you seeing in the logs?

**Comment by getrich20** [comment]
No the url is not configured in the setting but I do have my wan hosting
forwarding to Mattermost successfully already. The plugin is enabled, will
I see errors in the log of the plug in uploaded successfully? I try to use
the /reminder command and the slash word never appears.

**Comment by scottleedavis** [comment]
The SiteURL must be set in order for the plugin to function.  There will be an error in the logs saying site url must be set when plugin activated.  Remember a port may also used.  Something like http://localhost:8635.  After that, the slash command is /remind

**Comment by getrich20** [comment]
Okay cool I will give it a try soon as I get home. Thanks soo much for the
quick response!!! We are trying to incorporate this with my job and I was
banging my head trying to get it to work.

**Comment by getrich20** [comment]
That did the trick I was able to get the plugin up and running
successfully. Thank you so much for your time and help.
