### ISSUE TITLE
every + multiple days results in multiple entries in the list 

### ISSUE THREAD

**Issue by VincentSC** [scottleedavis/mattermost-plugin-remind#135]
When I do a "/remind ~town-square 'text' every monday and tuesday and wednesday and thursday and friday at 5pm" this results in duplicate entries in the list. When I add another reminder, it does not appear in the list. when I remove duplicate items, more than one duplicate items disappear and the newer ones suddenly appear. I end up with an empty list but it says the list should be 3. I'm pretty sure something goes wrong here.

Tested with "Remind Bot Mattermost Plugin (com.github.scottleedavis.mattermost-plugin-remind - 0.2.8)"

**Comment by scottleedavis** [comment]
@vincentSC this issue has been fixed in later versions.  Please upgrade to 0.4.1

**Comment by scottleedavis** [comment]
Let me know if you find otherwise! :)
