### ISSUE TITLE
Unable to add a bespoke reminder time

### ISSUE THREAD

**Issue by johnthompson365** [scottleedavis/mattermost-plugin-remind#138]
Hi, I was unable to add a reminder for 30 minutes time in the /remind form. It gave an error saying that 'No items matched 30 minutes' . Clicking schedule reminder cleared the field and then gave the 'field is required' error.

![image](https://user-images.githubusercontent.com/45836988/62176599-027e2b00-b2f7-11e9-8e66-84b878fbc0fb.png)

**Comment by scottleedavis** [comment]
Hi @johnthompson365.  The items selectable in the /remind interactive dialog are 20 minutes, 1 hour, 3 hours, tomorrow and next week.  Are you looking to add a custom value or additions?

**Comment by johnthompson365** [comment]
Hi Scott, thanks for responding. Yes, exactly. The standard reminder times are useful but I assumed when looking I would be able to input a custom time in the form similar to how I can in the slash command. I think this would be a useful addition to the functionality.

**Comment by scottleedavis** [comment]
Hi @johnthompson365 , I brought up dynamic entry into the select list in the interactive dialog, in the ~toolkit channel this morning, but got no responses. 
 https://community.mattermost.com/core/pl/tqdpe3ibetri9n1qehu1xydd6e 

After thinking about it some more, I think I could instead seed the list with more values (10 minutes, 20 minutes...  50 minutes, 1 hour, ... 23 hours, 1 day, etc) which would make the typed search work better for these cases.  I can move forward with this pretty easily if you agree, thoughts?

**Comment by johnthompson365** [comment]
Hey Scott. Sorry for the slow response. I've added my 2 cents to the community channel for Aaron to review. I think more options to start with would be a good first step, until we can have user-defined values. Many thanks.

**Comment by scottleedavis** [comment]
This will be part of release 0.4.4 (likely on friday this week for v5.14 mm release)

**Comment by johnthompson365** [comment]
Fantastic Scott, thanks for the update.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by scottleedavis** [comment]
@johnthompson365 this functionality has been released in v0.4.4 
https://github.com/scottleedavis/mattermost-plugin-remind/releases/tag/0.4.4

Let me know if youd like anything changed!
