### ISSUE TITLE
Confirm to the person that set the reminder that it is now complete

### ISSUE THREAD

**Issue by cedricroijakkers** [scottleedavis/mattermost-plugin-remind#139]
When a reminder is set from person A to person B, there is a confirmation message to person A notifying him that the reminder is set.

Person B receives the reminder at the set time, and has the option to mark it as complete. However, whne the reminder is marked as complete, it would be nice to notify person A that it has been completed. This is also the way Slack handles reminders and probably what people expect.

**Comment by scottleedavis** [comment]
An oversight on my part @cedricroijakkers, thank you for bringing it up.

**Comment by scottleedavis** [comment]
@cedricroijakkers v 0.4.2 have the functionality added.  Thank you for reporting this issue!

https://github.com/scottleedavis/mattermost-plugin-remind/releases/tag/0.4.2

**Comment by cedricroijakkers** [comment]
I'm getting a plugin crash now when trying to use the remind functionality.

I'm running mattermost docker container version `mattermost/mattermost-team-edition:5.13.2`

Logging on debug:

`{"level":"debug","ts":1565175952.8724635,"caller":"plugin/hclog_adapter.go:35","msg":"panic: time: missing Location in call to Time.In","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.8725088,"caller":"plugin/hclog_adapter.go:26","msg":"","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"error","ts":1565175952.8725,"caller":"mlog/log.go:172","msg":"RPC call ExecuteCommand to plugin failed.","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","error":"unexpected EOF"}
{"level":"debug","ts":1565175952.8725202,"caller":"plugin/hclog_adapter.go:35","msg":"goroutine 74 [running]:","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.87253,"caller":"plugin/hclog_adapter.go:35","msg":"time.Time.In(...)","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.8725386,"caller":"plugin/hclog_adapter.go:35","msg":"\t/usr/local/Cellar/go/1.12.5/libexec/src/time/time.go:1120","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.8725483,"caller":"plugin/hclog_adapter.go:35","msg":"main.(*Plugin).normalizeTime(0xc0001aeb40, 0xc0002878ce, 0x5, 0xc000298580, 0x0, 0xc000304912, 0x7, 0xc00038ea40)","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.8725588,"caller":"plugin/hclog_adapter.go:35","msg":"\t/Users/scottd/go/src/github.com/scottleedavis/mattermost-plugin-remind/server/parse.go:419 +0x2744","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.8725684,"caller":"plugin/hclog_adapter.go:35","msg":"main.(*Plugin).findWhenEN(0xc0001aeb40, 0xc000373520, 0xc0002bb200, 0xc00002bd6e)","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.8725774,"caller":"plugin/hclog_adapter.go:35","msg":"\t/Users/scottd/go/src/github.com/scottleedavis/mattermost-plugin-remind/server/parse.go:265 +0x25a6","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.8725874,"caller":"plugin/hclog_adapter.go:35","msg":"main.(*Plugin).findWhen(0xc0001aeb40, 0xc000373520, 0xb9c037, 0x1)","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.872597,"caller":"plugin/hclog_adapter.go:35","msg":"\t/Users/scottd/go/src/github.com/scottleedavis/mattermost-plugin-remind/server/parse.go:121 +0xd9","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.872607,"caller":"plugin/hclog_adapter.go:35","msg":"main.(*Plugin).ParseRequest(0xc0001aeb40, 0xc000373520, 0x0, 0xc00002bc98)","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.8726168,"caller":"plugin/hclog_adapter.go:35","msg":"\t/Users/scottd/go/src/github.com/scottleedavis/mattermost-plugin-remind/server/parse.go:48 +0x428","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.8726265,"caller":"plugin/hclog_adapter.go:35","msg":"main.(*Plugin).ScheduleReminder(0xc0001aeb40, 0xc000373520, 0xc000029b60, 0x1a, 0xc0002878c1, 0x12, 0x1)","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.8726366,"caller":"plugin/hclog_adapter.go:35","msg":"\t/Users/scottd/go/src/github.com/scottleedavis/mattermost-plugin-remind/server/scheduler.go:21 +0xef","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.8726466,"caller":"plugin/hclog_adapter.go:35","msg":"main.(*Plugin).ExecuteCommand(0xc0001aeb40, 0xc00020af50, 0xc00029cb40, 0x7ff2a0c980d8, 0xc0001aeb40)","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.872656,"caller":"plugin/hclog_adapter.go:35","msg":"\t/Users/scottd/go/src/github.com/scottleedavis/mattermost-plugin-remind/server/command.go:105 +0x7b8","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.872666,"caller":"plugin/hclog_adapter.go:35","msg":"github.com/mattermost/mattermost-server/plugin.(*hooksRPCServer).ExecuteCommand(0xc000079ba0, 0xc0002bac50, 0xc0002bafc0, 0x0, 0x0)","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.872679,"caller":"plugin/hclog_adapter.go:35","msg":"\t/Users/scottd/go/pkg/mod/github.com/mattermost/mattermost-server@v5.12.0+incompatible/plugin/client_rpc_generated.go:114 +0x78","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.8726892,"caller":"plugin/hclog_adapter.go:35","msg":"reflect.Value.call(0xc000091ce0, 0xc00008ea08, 0x13, 0xb9dafe, 0x4, 0xc000087f18, 0x3, 0x3, 0xc00005e300, 0x0, ...)","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.8727038,"caller":"plugin/hclog_adapter.go:35","msg":"\t/usr/local/Cellar/go/1.12.5/libexec/src/reflect/value.go:447 +0x461","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.872714,"caller":"plugin/hclog_adapter.go:35","msg":"reflect.Value.Call(0xc000091ce0, 0xc00008ea08, 0x13, 0xc00026cf18, 0x3, 0x3, 0x0, 0x0, 0x0)","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.872724,"caller":"plugin/hclog_adapter.go:35","msg":"\t/usr/local/Cellar/go/1.12.5/libexec/src/reflect/value.go:308 +0xa4","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.8727477,"caller":"plugin/hclog_adapter.go:35","msg":"net/rpc.(*service).call(0xc0001bbfc0, 0xc00009cf00, 0xc000083a50, 0xc000083a60, 0xc0000fca80, 0xc000256300, 0xa62920, 0xc0002bac50, 0x16, 0xa62960, ...)","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.8727593,"caller":"plugin/hclog_adapter.go:35","msg":"\t/usr/local/Cellar/go/1.12.5/libexec/src/net/rpc/server.go:384 +0x14e","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.8727684,"caller":"plugin/hclog_adapter.go:35","msg":"created by net/rpc.(*Server).ServeCodec","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.872778,"caller":"plugin/hclog_adapter.go:35","msg":"\t/usr/local/Cellar/go/1.12.5/libexec/src/net/rpc/server.go:481 +0x42b","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
{"level":"debug","ts":1565175952.8765624,"caller":"plugin/hclog_adapter.go:33","msg":"plugin process exited","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","wrapped_extras":"path/mattermost/plugins/com.github.scottleedavis.mattermost-plugin-remind/server/dist/plugin-linux-amd64pid161errorexit status 2"}
`

**Comment by scottleedavis** [comment]
@cedricroijakkers hmmm, that isn't expected.  I built/tested on master (5.13) without issue.  Lets get this issue solved.

Could you share:
1) what remind command you used to get this error?
2) the output from `/remind __user` ?

**Comment by scottleedavis** [comment]
I give that docker image a try myself

**Comment by scottleedavis** [comment]
@cedricroijakkers I ran the container mattermost/mattermost-team-edition:5.13.2 , and uploaded/tested the remind plugin and didn't see any issues.  

Seeing your error message, I am curious what might cause this.
1) are you using the 0.4.3 version?
2) Have you modified the container in anyway?

**Comment by cedricroijakkers** [comment]
I just tried it again with the following command:

`/remind @nicole to test reminders in 5 minutes`

This give the following error:

`Command with a trigger of '/remind' not found. Click here to send as a message.`

And this in the logs:

```
{"level":"error","ts":1565706274.4716115,"caller":"mlog/log.go:172","msg":"RPC call ExecuteCommand to plugin failed.","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","error":"unexpected EOF"}
{"level":"error","ts":1565706283.7584267,"caller":"plugin/health_check.go:95","msg":"Health check failed for plugin com.github.scottleedavis.mattermost-plugin-remind, error: Plugin process not found, or not responding"}
{"level":"error","ts":1565706283.758514,"caller":"mlog/log.go:172","msg":"RPC call OnDeactivate to plugin failed.","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","error":"connection is shut down"}
{"level":"warn","ts":1565706283.7585542,"caller":"plugin/hclog_adapter.go:51","msg":"error closing client during Kill","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","wrapped_extras":"errconnection is shut down"}
{"level":"warn","ts":1565706283.7585833,"caller":"plugin/hclog_adapter.go:53","msg":"plugin failed to exit gracefully","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
```

If I issue this command:

`/remind @nicole to test reminders in 5 minutes`

I get:

`Sorry, I didn’t understand. Try this: /remind [@someone or ~channel] [what] [when] or use /remind help.`

From the Reminderbot. And this in the logs:

`{"level":"error","ts":1565706357.3807003,"caller":"mlog/sugar.go:23","msg":"unable to find when","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}`

So that seems to be recognised correctly.

I have not modified the container in any way, Iḿ just running the following image in our Kubernetes cluster:

`mattermost/mattermost-team-edition:5.13.2`

Plugin version is indeed `0.4.3`.

**Comment by scottleedavis** [comment]
@cedricroijakkers I was able to replicate the issue, and running `apt-get tzdata` in the container seems to have fixed it.  Can you confirm?  It would be good to get this requested on the image repository too though it seems mattermost-docker already has it.  https://github.com/mattermost/mattermost-docker/blob/master/app/Dockerfile#L25 .  I am not sure how/where the mattermost-team-edition gets built from.

**Comment by scottleedavis** [comment]
Brought up the missing `tzdata` issue in the ~community channel https://community.mattermost.com/core/pl/ye3yupnse3n4pdmm653ixkd97o

**Comment by cedricroijakkers** [comment]
Meanwhile, mattermost team edition 5.14.0 has been released, they've switched from an ubuntu-based container to an alpine-based container, and it seems the tzinfo package is now part of the container. Reminders work out of the box without adding any packages now, so I think the issue can be closed.
