### ISSUE TITLE
Can add reminder successfully but doesn't trigger at time (or at all)

### ISSUE THREAD

**Issue by tutchmedia** [scottleedavis/mattermost-plugin-remind#15]
Hi, we have this set up correctly and everyone is able to add/list/clear a reminder. Unfortunately, nobody has been able to receive a reminder or notification.

Do you have any ideas what could be causing this or where to check first?

As a side note, the logs are showing the time as:

`2018-08-29T17:03:53.945+0100    debug   app/plugin_api.go:303   existing [{## user## me 1 16:35 [] 0001-01-01 00:00:00 +0000 UTC} {##$`

Note that the time isn't correct - could this be the cause?

Thanks

**Comment by scottleedavis** [comment]
@tutchmedia I am really putting all my energy into the native version of remind and not planning on doing bug fixes for the plugin.  That being said it could be a wing time issue certainly.

**Comment by scottleedavis** [comment]
https://github.com/scottleedavis/mattermost-server/tree/MM-10580
