### ISSUE TITLE
No action on snooze

### ISSUE THREAD

**Issue by tschlue** [scottleedavis/mattermost-plugin-remind#154]
Hi,

if I try to snooze reminder nothing happens/changes.

In log is the following

> ` {"level":"error","ts":1566201266.6626186,"caller":"mlog/sugar.go:23","msg":"SqlPostStore.GetSingle: Unable to get the post, id=461f89qoz7rtjnbmc4k5jqhkrrsql: no rows in result set","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}`
> `{"level":"error","ts":1566201266.664399,"caller":"mlog/log.go:172","msg":"Action integration error","path":"/mattermost/api/v4/posts/461f89qoz7rtjnbmc4k5jqhkrr/actions/nenocukggfdy9eucpu9yanfz9c","request_id":"hxxkb6z1hpgfbgt1cx91yz13ea","ip_addr":"10.144.153.28","user_id":"c7up9ghhpjydzbaw7x1ebwo4zc","method":"POST","err_where":"DoActionRequest","http_code":400,"err_details":"status=400"}`

Plugin Version: 0.4.3
Mattermost Version: 5.13.2

**Comment by scottleedavis** [comment]
Hi @tschlue , Thank you for reporting this!  This is fixed in v0.4.4 https://github.com/scottleedavis/mattermost-plugin-remind/releases/tag/0.4.4 . 

Note this version requires mattermost 5.14.

**Comment by tschlue** [comment]
Thanks

**Comment by Roy-Orbison** [comment]
I'm still seeing this issue in v0.4.4 on Mattermost v5.17.1

**Comment by Roy-Orbison** [comment]
@scottleedavis this problem occurs on trying to snooze a recurring reminder. I seem to be able to snooze those without a schedule.
