### ISSUE TITLE
Reminder crashes

### ISSUE THREAD

**Issue by tschlue** [scottleedavis/mattermost-plugin-remind#155]
After upgrading yesterday Mattermost to 5.14 and the reminder to 0.4.4 today the plugin was stopped (by itself of or mattermost) due to a lot of errors.

> `{"level":"error","ts":1566374506.8136456,"caller":"api4/websocket.go:28","msg":"websocket connect err: websocket: request origin not allowed by Upgrader.CheckOrigin"}`
> `{"level":"error","ts":1566374506.8137093,"caller":"mlog/log.go:173","msg":"Failed to upgrade websocket connection","path":"/mattermost/api/v4/websocket","request_id":"xphyixw7htf47e7p88etupkdfh","ip_addr":"10.144.156.248","user_id":"6bwcgiotw3fk9dr3mzkozwxa5o","method":"GET","err_where":"connect","http_code":500,"err_details":""}`
> `{"level":"error","ts":1566374509.8402839,"caller":"api4/websocket.go:28","msg":"websocket connect err: websocket: request origin not allowed by Upgrader.CheckOrigin"}`
> `{"level":"error","ts":1566374509.8403947,"caller":"mlog/log.go:173","msg":"Failed to upgrade websocket connection","path":"/mattermost/api/v4/websocket","request_id":"kd4m737sfjre3p51mzyukmgpzc","ip_addr":"10.144.156.248","user_id":"6bwcgiotw3fk9dr3mzkozwxa5o","method":"GET","err_where":"connect","http_code":500,"err_details":""}`
> `{"level":"error","ts":1566374537.4792485,"caller":"mlog/log.go:173","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","error":"unexpected EOF"}`
> `{"level":"error","ts":1566374537.4807625,"caller":"mlog/log.go:173","msg":"Action integration error","path":"/mattermost/api/v4/posts/ghyqpraj9fnn5qxfski4qg65dy/actions/zr6qd3f9kfyfucys5yddtw15cc","request_id":"ccetx9ukppbpfnaimszc5wdnbc","ip_addr":"10.144.157.66","user_id":"7rehqjww43r4tyo5mrmewj7tfc","method":"POST","err_where":"DoActionRequest","http_code":400,"err_details":"status=500"}`
> `{"level":"error","ts":1566374550.488675,"caller":"mlog/log.go:173","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","error":"connection is shut down"}`
> `{"level":"error","ts":1566374550.4893534,"caller":"mlog/log.go:173","msg":"Action integration error","path":"/mattermost/api/v4/posts/ghyqpraj9fnn5qxfski4qg65dy/actions/i49sh7yej7n3dci9db3kkbm65y","request_id":"1c6943x8eb8yxmbjbfwquqd1ue","ip_addr":"10.144.157.66","user_id":"7rehqjww43r4tyo5mrmewj7tfc","method":"POST","err_where":"DoActionRequest","http_code":400,"err_details":"status=500"}`
> `{"level":"error","ts":1566374555.4889648,"caller":"mlog/log.go:173","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","error":"timeout waiting for accept"}`
> `{"level":"error","ts":1566374555.4889503,"caller":"mlog/log.go:173","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","serve_http_stream_id":4,"error":"timeout waiting for accept"}`
> `{"level":"error","ts":1566374561.0113795,"caller":"plugin/health_check.go:89","msg":"Health check failed for plugin com.github.scottleedavis.mattermost-plugin-remind, error: Plugin RPC connection is not responding"}`
> `{"level":"error","ts":1566374561.011434,"caller":"mlog/log.go:173","msg":"RPC call OnDeactivate to plugin failed.","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","error":"connection is shut down"}`
> `{"level":"warn","ts":1566374561.0114772,"caller":"plugin/hclog_adapter.go:51","msg":"error closing client during Kill","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind","wrapped_extras":"errconnection is shut down"}`
> `{"level":"warn","ts":1566374561.0114977,"caller":"plugin/hclog_adapter.go:53","msg":"plugin failed to exit gracefully","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}`

**Comment by tschlue** [comment]
I realised that error stops appearing. A user has used the ip address of the mattermost server instead of the url. Other plugin didn't has a problem with it.

**Comment by tschlue** [comment]
Again

![grafik](https://user-images.githubusercontent.com/14072748/63437802-8d040700-c42b-11e9-85a1-42feea117239.png)

Looks like it wasn't the problem.

**Comment by scottleedavis** [comment]
@tsclue what is the type of server?  Docker, manual install,?  This looks like a big error and I'd like to reproduce it.

**Comment by tschlue** [comment]
Manual

**Comment by tschlue** [comment]
I think it is still the problem when connection URL not fits correctly. I moved the mattermost url from https://server.com to https://server.com/mattermost but the old url is rewritten to the new one.

**Comment by scottleedavis** [comment]
@tschlue I setup a docker and debian install of 5.14 this evening, and although had some issue with the buttons not working with debian (see issue #148 ), the plugin installed and ran without error on both.  I am curious about what might be going on with the url rewrite you mentioned, though I don't think that would cause the plugin crash.

What operating system is this running on?
Does [matterpoll](https://github.com/matterpoll/matterpoll) work?

@lieut-data (pardon the ping), is this a trivial or known issue to fix?  I looked [here](https://docs.mattermost.com/administration/plugins.html), however I didn't find anything specifically addressing plugin crashes.  e.g. `Plugin failed to ServeHTTP, RPC call failed`, `Plugin failed to ServeHTTP, muxBroker couldn't accept connection`

**Comment by tschlue** [comment]
@scottleedavis Matterpoll works fine. Mattermost is running on centos 7.

**Comment by scottleedavis** [comment]
@tschlue that error is different than the original one you posted.  It should only occur once the plugin is running though.  is the plugin running currently with just that error on triggered reminder?  Could you share the `/remind .....` string you used?

**Comment by tschlue** [comment]
@scottleedavis at the moment, yes. I wrote all user to correct the url path. So it could be still the reason for the errors. Which `/remind ...` string do you mean? Maybe I don't know beacause it's used by an user.

**Comment by tschlue** [comment]
@scottleedavis No, I don't. But it could come from another user. I can't reproduce these errors :(.

**Comment by tschlue** [comment]
I think this is okay.
