### ISSUE TITLE
cant find config.json file

### ISSUE THREAD

**Issue by hobsRKM** [scottleedavis/mattermost-plugin-remind#16]
Cannot find the config.json file.
Is readme outdated?
Where do i set exactly the site url?

**Comment by scottleedavis** [comment]
Hi @hobsRKM

7 days ago this plugin wasn’t in a workable state.  While it is more stable now, I am planning on it be fully usable later this week.  The config for siteURL comes from the server/config/config.json running on the server.  Readme.md is up to date, and please point out anything not correct. :)
