### ISSUE TITLE
Delete message missing name

### ISSUE THREAD

**Issue by Roy-Orbison** [scottleedavis/mattermost-plugin-remind#161]
#### Summary
Delete message missing name of reminder

#### Steps to reproduce
1. Create a reminder
2. View it with `/remind list`
3. Click its *Delete* button

#### Expected behavior
Confirmation should say:
>I’ve deleted the reminder "*name of reminder*".

#### Observed behavior (that appears unintentional)
Confirmations says
>I’ve deleted the reminder "".

#### Server configuration
**Operating system:** Debian

**Mattermost version:** 5.12.4

**Matterpoll version:** ???

**Remind Bot version:** 0.4.1

**Updated from an older Remind bot version or fresh install:** I forget

#### Additional context
Looks like a simple issue of the reminder name being lost on its way to the message.

**Comment by scottleedavis** [comment]
@Roy-Orbison are you able to update to v0.4.4 (requires mattermost 5.14)?  This has been fixed along the way

**Comment by Roy-Orbison** [comment]
Upgraded Mattermost and Remind Bot that problem's gone, but got others.
