### ISSUE TITLE
Deleting Reminder Resets Date

### ISSUE THREAD

**Issue by ewwollesen** [scottleedavis/mattermost-plugin-remind#166]
#### Summary
Deleting a reminder resets the message date to December 31, 1969.

#### Steps to reproduce
1. Create a reminder the date shows today's date
2. Delete the reminder the date resets to Dec 31, 1969

#### Expected behavior
I would expect it to keep the date the same even when deleted.

#### Observed behavior (that appears unintentional)
![Screen Shot 2019-09-30 at 10 34 26 AM](https://user-images.githubusercontent.com/50209602/65893990-93609980-e36e-11e9-982d-900fa02a2a64.png)
![Screen Shot 2019-09-30 at 10 34 36 AM](https://user-images.githubusercontent.com/50209602/65894015-9e1b2e80-e36e-11e9-9b4d-6560d90de86b.png)

#### Server configuration
**Operating system:**
Rhel 7
**Mattermost version:**
5.14.2
**Remind version:**
0.4.4
**Updated from an older Remind bot version or fresh install:**
Updated from 0.3.1

<summary>Mattermost server logs</summary>
It didn't seem to put anything in the logs. I saw where the new occurrence was created, but it didn't log anything upon deletion.

#### Additional context
It's not a huge issue, but a couple users mentioned it so thought I would pass it along because I didn't see any other issues related to it.

**Comment by scottleedavis** [comment]
@hanzei pardon the ping, however I have seen this for most ephemeral post interactions in the past, and brought it up once I believe on community some months ago.  Is this something to bring up on user voice or a jira?

**Comment by scottleedavis** [comment]
@ewwollesen as this is handled by mattermost-server and mattermost-webapp, not in scope to be fixed by this plugin.
