### ISSUE TITLE
Really requires 5.10.0 ?

### ISSUE THREAD

**Issue by bradonkanyid** [scottleedavis/mattermost-plugin-remind#17]
I'd love to use this plugin (even though it's WIP), but it says recently that it requires MM 5.10. We run 5.9 currently, and I guess I can wait, but if there's no actual 5.10 features, maybe we could roll it back to 5.9?

**Comment by scottleedavis** [comment]
Hi @bradonkanyid,

Great point!  And today I converted the remind user to use a bot account only available in 5.10.  :)
