### ISSUE TITLE
CORS error on button click

### ISSUE THREAD

**Issue by gfra54** [scottleedavis/mattermost-plugin-remind#171]
#### Summary
some basic feature are not working

#### Steps to reproduce
1. See reminder `/remind list`
2. Click on any reminder's button
3. A CORS erros show up in ther console : 
```
Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://api.segment.io/v1/m. Raison : échec de la requête CORS.
```
(sorry for the french ouput, but you get the gist)

#### Expected behavior
Something should happen when I click on "Close list" or "Mark as complete"
#### Observed behavior (that appears unintentional)
Nothing happens after I click

#### Server configuration
**Operating system:**
Debian 9

**Mattermost version:**
 5.16.2
**Remind version:**
last (0.4.4)

**Updated from an older Remind bot version or fresh install:**
fresh install

**Comment by scottleedavis** [comment]
@gfra54 does this still occur it latest Mattermost version?

**Comment by scottleedavis** [comment]
@gfra54 I added functionality for plugins no not route to external URL I believe in 5.18...

**Comment by scottleedavis** [comment]
https://github.com/mattermost/mattermost-server/pull/12156

**Comment by gfra54** [comment]
Yes it seems to work now. Thank you very much, `/remind` is so useful 👍
