### ISSUE TITLE
Not all options are visible

### ISSUE THREAD

**Issue by stefnats** [scottleedavis/mattermost-plugin-remind#172]
As seen in the screenshot not all time options are visible:

<img width="608" alt="Bildschirmfoto 2020-01-06 um 10 02 43" src="https://user-images.githubusercontent.com/1174473/71807482-b389ae00-306b-11ea-994e-472c3f2bbb94.png">

Mattermost: 5.18
Plugin: 0.4.4
Used in Mattermost Desktop Client (macOS)

**Comment by scottleedavis** [comment]
@hanzei this is due to 'large list' situation.  Unless the fundamental MM component is updated, this is a won't fix.
