### ISSUE TITLE
Funny Entry Crashes Remind

### ISSUE THREAD

**Issue by blark012** [scottleedavis/mattermost-plugin-remind#175]
#### Summary
entering /remind me asdasd every today causes the plugin to crash

#### Steps to reproduce
1. Go to any channel
2. Post /remind me asdasd every today

#### Expected behavior
a user was trying to spam a co-worker and unintentionally crashed the plugin

#### Observed behavior (that appears unintentional)
What did you see happen? Please include relevant error messages and/or screenshots.

#### Server configuration
**Operating system:**

**Mattermost version:**
5.17.0
**Remind version:**
0.4.4
**Updated from an older Remind bot version or fresh install:**

<details>
<summary>Mattermost server logs</summary>

```
Insert your Mattermost server logs here
```
</details>

**Comment by Chubik** [comment]
ServerLog:
{"level":"debug","ts":1587995042.5387802,"caller":"plugin/hclog_adapter.go:53","msg":"panic: runtime error: index out of range [1] with length 1","plugin_id":"com.github.scottleedavis.mattermost-
plugin-remind"}

I think normalizeDate method should be rewritten.

I have found a similar issue.
reminder request:  /remind me test 30th of April
log: 
{"level":"debug","ts":1587995746.0320342,"caller":"plugin/hclog_adapter.go:53","msg":"panic: runtime error: index out of range [1] with length 1","plugin_id":"com.github.scottleedavis.mattermost-
plugin-remind"}

issue of my request is here:
file: parse.go
		mon, mErr := strconv.Atoi(parts[0])
		day, dErr := strconv.Atoi(parts[1])
		year, yErr := strconv.Atoi(parts[2])
len of parts = 1

**Comment by scottleedavis** [comment]
@Chubik are you able to issue a PR to resolve this issue?

**Comment by Chubik** [comment]
> @Chubik are you able to issue a PR to resolve this issue?

sorry for delay, missed your message.
Ill add PR fixes of my issue till end of the week or on start of the next one.
Unfortunately, I didnt investigated issue blark012, Ill try to check too.

**Comment by scottleedavis** [comment]
https://github.com/scottleedavis/mattermost-plugin-remind/pull/184
