### ISSUE TITLE
Cannot remind private channel

### ISSUE THREAD

**Issue by jellard1** [scottleedavis/mattermost-plugin-remind#183]
#### Summary
Cannot remind all members of private channel.

#### Steps to reproduce
1. Type /remind
2. Begin typing ~[private channel name]
3. Only public channels appear.
4. No reminders appear
5. Workaround can be to @ every person in room, but reminders appear in DM from Remindbot and not in the private channel.

#### Expected behavior
Remind private channel.

#### Server configuration
Running mattermost container images on dockerhub on Ubuntu 18.04

**Mattermost version**
5.20.1

**Remind version:**
4.4

**Updated from an older Remind bot version or fresh install:**

**Comment by scottleedavis** [comment]
@jellard1 I believe that is more an issue in mattermost-webapp.  Try typing the private channel itself, and see if it shows up there (it should).

**Comment by Dave-Kay** [comment]
> @jellard1 I believe that is more an issue in mattermost-webapp. Try typing the private channel itself, and see if it shows up there (it should).

Having the issue myself, Adressing private Channel like "~private_channel" it doesn't work, though stating it will remind the channel.

**Comment by scottleedavis** [comment]
@hanzei what is needed so that a bot account can message a private channel?

**Comment by hanzei** [comment]
That is not a limitation by bot accounts. The webapp just shows public channels for auto completion of `~`.

**Comment by scottleedavis** [comment]
not a bug
