### ISSUE TITLE
Click on button errors

### ISSUE THREAD

**Issue by Philmod** [scottleedavis/mattermost-plugin-remind#194]
#### Summary
When I click on any button (Mark as complete, delete, etc...), the http call fails with: `{"id":"api.post.do_action.action_integration.app_error","message":"Action integration error","detailed_error":"","request_id":"j9w5n5qozjntfnj58gkcbesrah","status_code":400}`

#### Expected behavior
Perform the action and returns some feedback.

#### Observed behavior (that appears unintentional)
Nothing. I had to go to the browser console to see there was an error.

#### Server configuration
**Operating system:**
Linux

**Mattermost version:**
5.14.0

**Remind version:**
0.4.4

**Updated from an older Remind bot version or fresh install:**
Fresh install

<details>
<summary>Mattermost server logs</summary>

```
{"level":"error","ts":1610741146.9604926,"caller":"mlog/log.go:173","msg":"Action integration error","path":"/api/v4/posts/3copiqynebry5jooodbpwtopbh/actions/mrxtdjygdpgzjbjqkh8qf9ppcc","request_id":"9nnxf3q3bpbf9mg4wn96obybne","ip_addr":"68.199.47.235","user_id":"9oyrfauyc3fo8nt111t883sbie","method":"POST","err_where":"DoActionRequest","http_code":400,"err_details":"status=401"}
```
</details>

#### Additional context
Our mattermost installation is protected behind Google Cloud IAP, but I'm guessing these calls should call "localhost".

**Comment by hanzei** [comment]
The mattermost version you are using is quite old. Could you please update to a newer one?

**Comment by Philmod** [comment]
Upgrading to `5.31` fixed the problem, thanks.
