### ISSUE TITLE
Release last fixes on master

### ISSUE THREAD

**Issue by jdauphant** [scottleedavis/mattermost-plugin-remind#205]
Hello @scottleedavis , there is 2 fixes in the master, can you release it on a new release ?

Thanks,
Julien

**Comment by scottleedavis** [comment]
Is @hanzei  available to do this?

**Comment by hanzei** [comment]
A new release has been cut: https://github.com/scottleedavis/mattermost-plugin-remind/releases/tag/v0.4.5
