### ISSUE TITLE
No reminders sent on MM 6.1

### ISSUE THREAD

**Issue by Aephex** [scottleedavis/mattermost-plugin-remind#210]
#### Summary
Reminders are not sent to users after they are created on Mattermost 6.1

#### Steps to reproduce
1. Create any reminder and set the user to yourself via @ tag or `me`.
2. Check logs when it should have sent.

#### Expected behavior
A reminder message is sent.

#### Observed behavior (that appears unintentional)
No channel created or message sent.

#### Server configuration
**Operating system:**
Ubuntu

**Mattermost version:**
6.1.0

**Remind version:**
0.4.5

**Updated from an older Remind bot version or fresh install:**
Fresh Install

<details>
<summary>Mattermost server logs</summary>

```
{"timestamp":"2021-12-03 16:15:36.616 Z","level":"error","msg":"failed to create channel createDirectChannel: A direct channel cannot be created between these users because they do not share a team in common., ","caller":"app/plugin_api.go:898","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
...
 {"timestamp":"2021-12-03 16:31:01.386 Z","level":"error","msg":"failed to find target user @nich","caller":"app/plugin_api.go:898","plugin_id":"com.github.scottleedavis.mattermost-plugin-remind"}
```
</details>

#### Additional context
No other context.

**Comment by chadbillanderson** [comment]
I am also having this issue, on MM v6.1.0. This is my first time installing Remind Bot (v0.4.5)

**Comment by chadbillanderson** [comment]
I discovered the source of the problem. 
`System Console > Site Configuration > Users and Teams`
I had `Enable users to open Direct Message channels with:` set to `Any member of the team` --- after changing to `Any user on the Mattermost server`, everything is working as expected.

**Comment by mrmonkington** [comment]
If this global permissions change isn't acceptable (it wasn't for us) you can add "remindbot" to whichever teams it should have posting rights to.
