### ISSUE TITLE
Snoozed dropdown only drops 'up'

### ISSUE THREAD

**Issue by scottleedavis** [scottleedavis/mattermost-plugin-remind#37]
reported by @esethna 

![image](https://community.mattermost.com/files/frzypcx7atnm5n9xwn5kyycshy/public?h=y96wXEse10_ovuVxnwj6Lan5fdZzdAwG6hE4SbQSUio)

will require mattermost-webapp changes

**Comment by hanzei** [comment]
@jasonblais Is this by design or a bug with Mattermost?

**Comment by jasonblais** [comment]
It's known https://mattermost.atlassian.net/browse/MM-14489

**Comment by scottleedavis** [comment]
https://github.com/mattermost/mattermost-server/issues/10627

**Comment by scottleedavis** [comment]
closing this as it is an external dependency, and it will be handled in time.
