### ISSUE TITLE
/remind help visible for all users in channel

### ISSUE THREAD

**Issue by JtheBAB** [scottleedavis/mattermost-plugin-remind#63]
Hi Scott

When someone types

/remind help

Everyone in the channel can read it.

Best regards

JtheBAB

**Comment by hanzei** [comment]
Technically speak the problem is, that bot accounts can't create ephemeral posts. Setting the user name and user icon manually doesn't seam ideal.

I opened a discussion at https://community.mattermost.com/core/pl/4t54caacc3b978irq3u86qnfsr

**Comment by scottleedavis** [comment]
Going to take that on. https://github.com/mattermost/mattermost-server/issues/10640

**Comment by scottleedavis** [comment]
As a stop gap @JtheBAB and @hanzei  I have enabled ephemeral command responses, and left commented code in to renable once ephemeral bot posts are working.  (scheduled for 5.12)

This is done in v0.1.3 https://github.com/scottleedavis/mattermost-plugin-remind/releases/tag/v0.1.3
