### ISSUE TITLE
Post /remind list in the same channel

### ISSUE THREAD

**Issue by hanzei** [scottleedavis/mattermost-plugin-remind#69]
The list created via `/remind list` should be posted as a ephemeral message in the same channel as the command.

See https://community.mattermost.com/core/pl/1wpofu9qktni8g3jbd5kguoseh for the discussion.

**Comment by scottleedavis** [comment]
@hanzei I am having some issues that I will bring up on the extensions channel.  https://community.mattermost.com/core/channels/developer-toolkit

You are welcome to also help me debug if you have time, here is the branch https://github.com/scottleedavis/mattermost-plugin-remind/tree/Issue%2369_%2365

Updating the ephemeral post (for example with paging) seems to work and then stop after 1 or 2 interactions.  I haven't figured it out yet.

**Comment by scottleedavis** [comment]
Created an issue for mattermost-server for UpdateEphemeralPost only handling one update.  https://github.com/mattermost/mattermost-server/issues/10832

**Comment by scottleedavis** [comment]
Turns out, I was wrong and it is possible to repeatedly update an ephemeral post.  Going to continue this issue.

**Comment by scottleedavis** [comment]
Completed with PR #99
