### ISSUE TITLE
bugs found in functional testing on cluster 

### ISSUE THREAD

**Issue by scottleedavis** [scottleedavis/mattermost-plugin-remind#71]
~~### 1) display time is correct on local, but not on cluster~~ . fixed by timezone fix
<img width="417" alt="right-display-local" src="https://user-images.githubusercontent.com/2914443/56785540-854c9280-67aa-11e9-8ffb-0941c1d535e4.png">
<img width="402" alt="wrong-display-community" src="https://user-images.githubusercontent.com/2914443/56785545-8a114680-67aa-11e9-86ab-f0bfe4db9aa0.png">

~~### 2) 'at' time fires local, but not on cluster~~ . fixed by timezone fix
<img width="475" alt="'at' time fires local" src="https://user-images.githubusercontent.com/2914443/56785558-9dbcad00-67aa-11e9-81c3-2007bc850ed3.png">
<img width="366" alt="'at' time never fires community" src="https://user-images.githubusercontent.com/2914443/56785561-a1e8ca80-67aa-11e9-8d70-f30a8e3cf77f.png">

**Comment by scottleedavis** [comment]
`/remind me check at <some time>` is not triggering

**Comment by scottleedavis** [comment]
'/remind me call mom tomorrow ' is not parsing

**Comment by scottleedavis** [comment]
look at a call, it appears 'at' when handling is going to next day
`{67nfrrwq5if6ietem9k8i8j
dho skawtus me work at 9:30pm {67nfrrwq5if6ietem9k8i8jdho y1jsaejehtgqzm3gmjb91burdr skawtus you work at 9:30pm [{k
s9p1aan9jyef845prz149aoua skawtus y1jsaejehtgqzm3gmjb91burdr  2019-04-28 21:30:00 +0000 UTC 0002-02-02 00:00:00 +00
00 UTC}] 0002-02-02 00:00:00 +0000 UTC}}`

**Comment by tschlue** [comment]
Mattermost Version: 5.10.0
remind Version: 0.2.0




![mmtimezonebug](https://user-images.githubusercontent.com/14072748/57068765-f4f2de00-6cd2-11e9-94d4-c99265dfaa8d.png)

**Comment by scottleedavis** [comment]
@tschlue could you share the command that produced this output?

**Comment by tschlue** [comment]
`/remind me in 1 min`

**Comment by scottleedavis** [comment]
Ah!  that should return an error instead of schedule a reminder.  thank you.
`/remind me a message in 1 min` (e.g. /remind me|@user|~channel message time)

**Comment by tschlue** [comment]
Okay, but this doesn't fix the time problem.

**Comment by tschlue** [comment]
I think would like to use empty messages, just to remind me to look at mattermost or to wakeup a channel.

**Comment by scottleedavis** [comment]
For empty messages you can use empty double quotes.  e.g. `/remind me "" in 1 min`.  Slackbot doesn't permit empty messages except in this fashion as well.

I hadn't noticed the time issue until now.  Could you share `/remind __user` ?   What server tech are you using?  docker?   debian?  other?  Could you try Experimental -> timezone enabled?

**Comment by tschlue** [comment]
System
17:46(Only visible to you)
×
locale: en
location: America/Atikokan

**Comment by scottleedavis** [comment]
@tschlue could you try the bot-test plugin to see if it matches the header time of the post?
`/test-time` returns time.  should match post header
https://github.com/scottleedavis/mattermost-plugin-bot-test/releases/tag/v0.1.2

**Comment by tschlue** [comment]
![grafik](https://user-images.githubusercontent.com/14072748/57288546-f4cf5580-70b9-11e9-912f-655ea14a564c.png)

**Comment by scottleedavis** [comment]
@tschlue I could replicate this by changing my timezone on my laptop.  I could also fix it by enabling experimental timezone support.  Would you try that out and let me know?

System Console -> Experimental Features -> Timezone  = true

**Comment by tschlue** [comment]
@scottleedavis This fix the problem apparently but is this necessary?

**Comment by scottleedavis** [comment]
@tschlue No, however it is quickest.  I created https://github.com/scottleedavis/mattermost-plugin-remind/issues/94 to take webapp timezone detection into account.

**Comment by tschlue** [comment]
thanks
