### ISSUE TITLE
Add webapp feature for reminders from post 'more actions' ellipsis

### ISSUE THREAD

**Issue by scottleedavis** [scottleedavis/mattermost-plugin-remind#73]
Slack has this feature.
![slack-reminder-ellipsis](https://user-images.githubusercontent.com/2914443/56820821-bd32f480-6801-11e9-89a3-db114a11e22d.gif)

**Comment by zvukoper** [comment]
That would be fantastic!!!!

**Comment by zvukoper** [comment]
Is it possible to extend that feature further by adding not only "remind me about this", but "remind [who]" too?

**Comment by scottleedavis** [comment]
While possible, I feel in this context the quick menu selection works be come slowee and less intuitive to target "who" @zvukoper...  Open to ideas though

**Comment by scottleedavis** [comment]
Have made good progress and learning on this.

Having a submenu in the post action menu will be tricky as the menu registry expects it to only be text.  Not impossible though to modify webapp to allow it.

Next best is a single menu item that opens up an interactive dialog.  Currently this isn't possible as dialogs need a triggerId and that isn't currently possible from a webapp interaction.

I followed the second approach here https://github.com/scottleedavis/mattermost-plugin-remind/tree/issue_73

Will continue with this when more progress is made on either front.

**Comment by scottleedavis** [comment]
@zvukoper @esethna Here is the state of things on post drop down reminder scheduling.
I haven't gotten a response from mm on adding submenu's to the post drop down menu, or if interactive dialogs can be scheduled from the webapp.  (though the later has a discussion around it)  However, I am able to get the flow working with a test for '1 hour' scheduling from the post drop down menu.

![dropdown](https://user-images.githubusercontent.com/2914443/57964593-89bd2480-78ec-11e9-8cdb-97e64cf025e2.gif)

There is a prelease binary if you'd like to try it out
https://github.com/scottleedavis/mattermost-plugin-remind/releases/tag/v0.2.5-dropdowndemo

I will keep this branch around in case either opportunity opens up to complete it.  Although I could add the 5 (20min, 1hr, 3hr, tomorrow, next week) schedule option in the main post drop down menu now, it seems to take up a lot of room.

**Comment by towolf** [comment]
>  Although I could add the 5 (20min, 1hr, 3hr, tomorrow, next week) schedule option in the main post drop down menu now, it seems to take up a lot of room.

How about 3 new menu items? `1 hour`, `tomorrow`, `next week`

**Comment by scottleedavis** [comment]
@towolf I am currently planning on staying with 1, and use the InteractiveDialog to select which time.  https://github.com/mattermost/mattermost-server/pull/10914

If we get submenus in post menu dropdowns I'd aim towards that.  

I feel more than one addition to the menu is to cluttered.  3/5 on this.  :)

**Comment by bbodenmiller** [comment]
> I haven't gotten a response from mm on adding submenu's to the post drop down menu

@scottleedavis where is the conversation ongoing?

**Comment by scottleedavis** [comment]
apologies @bbodenmiller for not having updated sooner, however the team approved the idea and I am working on the help wanted ticket to implement the functionality https://mattermost.atlassian.net/browse/MM-16946

**Comment by scottleedavis** [comment]
progress, still needs unit tests and mobile web view.
<img width="379" alt="Screen Shot 2019-07-26 at 5 23 54 PM" src="https://user-images.githubusercontent.com/2914443/61987293-45c05d00-afca-11e9-89a7-f4fc6779fde5.png">

**Comment by bbodenmiller** [comment]
> apologies @bbodenmiller for not having updated sooner, however the team approved the idea and I am working on the help wanted ticket to implement the functionality https://mattermost.atlassian.net/browse/MM-16946

@scottleedavis nice! Look forward to it!

**Comment by scottleedavis** [comment]
@jthebob I believe this will do what you mentioned on community.  :)

**Comment by scottleedavis** [comment]
I believe this will do what you mentioned in community @JtheBAB

**Comment by esethna** [comment]
@scottleedavis how is this feature going @scottleedavis? Looking forward to it!

**Comment by scottleedavis** [comment]
@esethna The plugin webapp development is complete however the functionality in mattermost-webapp is currently in QA.  
https://github.com/mattermost/mattermost-webapp/pull/3357

Scheduled for  5.18

**Comment by esethna** [comment]
Sweet!

**Comment by bbodenmiller** [comment]
@scottleedavis how's this coming along?

**Comment by scottleedavis** [comment]
not in active development currently .  My manager time off for development time is scarce these days.

@hanzei ?

**Comment by scottleedavis** [comment]
https://www.linkedin.com/posts/skawtus_remind-plugin-activity-6662399044964401152-aCZw

**Comment by bbodenmiller** [comment]
@scottleedavis so started at https://github.com/scottleedavis/mattermost-plugin-remind/pull/137? Any general feelings of what's left to do besides testing?

**Comment by scottleedavis** [comment]
@bbodenmiller yes and there is new structure for creation of the menu function that I completed in mattermost-webapp.  That would be the place to look into.

please see the [mattermost-plugin-demo repo](https://github.com/mattermost/mattermost-plugin-demo/search?q=submenu&unscoped_q=submenu)
![Screen Shot 2020-05-04 at 8 06 55 AM](https://user-images.githubusercontent.com/2914443/80981097-5534c800-8dde-11ea-96ec-94d26d11b0d0.png)

I would recommend taking those examples, and applied it to the existing branch PR.   Also I would recommend fixing the merge conflicts.

**Comment by scottleedavis** [comment]
@kaakaa you had asked what needs to be completed for the PR.  It is matching the code found in the mattermost-plugin-demo and changed in the PR. ☝️ 

https://community.mattermost.com/core/pl/4aiwoyz413fjxyqoejaomctpuh

**Comment by Tragen** [comment]
Anything we can do to get this feature working?

**Comment by scottleedavis** [comment]
I will pick this up.

**Comment by esethna** [comment]
@scottleedavis how's this going? Would LOVE to see this in the product! Let us know if you need assistance :)

**Comment by Philmod** [comment]
Any update?

**Comment by the-black-wolf** [comment]
Hi, any chance we can see this in prod? We have, as many, migrated to Mattermost when Slack stole our 90+ days messages. A lot of teams were using this feature, ours included. mattermost/community#164 appears to not even start and you guys are the closest to the solution.

**Comment by sparfenov** [comment]
Hi! how it's going? We would be very grateful if you release this feature

**Comment by JtheBAB** [comment]
One of the near upcoming Mattermost version has this feature directly inside without the plugin. It’s already on community.mattermost.com

**Comment by scottleedavis** [comment]
Awesome, and confirmed. Thanks @JtheBAB

**Comment by errotu** [comment]
Just some background (as I was wondering when it will be added to a released version):
- the backend of the reminder function was added [in this PR](https://github.com/mattermost/mattermost-server/pull/20555)
- the frontend changes are discussed [here](https://github.com/mattermost/mattermost-webapp/pull/10688) and [here](https://github.com/mattermost/mattermost-webapp/pull/12007)

As it is part of the v7.10 milestone, it should probably be included in the April 16 release. :tada:
