### ISSUE TITLE
use different URL for each integration action

### ISSUE THREAD

**Issue by scottleedavis** [scottleedavis/mattermost-plugin-remind#81]
right now they all share the same url

**Comment by scottleedavis** [comment]
https://github.com/matterpoll/matterpoll/blob/master/server/plugin/api.go#L76-L90

**Comment by scottleedavis** [comment]
https://github.com/gorilla/mux

**Comment by scottleedavis** [comment]
update to use gorilla/mux 86d2040

**Comment by hanzei** [comment]
Awesome! :tada:
