### ISSUE TITLE
Show ephemeral post after creating a reminder via an Interactive Dialog

### ISSUE THREAD

**Issue by hanzei** [scottleedavis/mattermost-plugin-remind#82]
After creating a reminder via an Interactive Dialog no confirmation dialog is shown. It would help if the same message is shown as after the "normal" `/remind ...` command.

Follow up on https://github.com/scottleedavis/mattermost-plugin-remind/issues/75

**Comment by scottleedavis** [comment]
fixed, will be released with 0.2.0
