### ISSUE TITLE
Messanges in Interactive Dialog are not localized

### ISSUE THREAD

**Issue by hanzei** [scottleedavis/mattermost-plugin-remind#83]
![Screenshot from 2019-04-29 10-56-45](https://user-images.githubusercontent.com/16541325/56885754-83662600-6a6d-11e9-8169-6819281e8dee.png)

Running on `master` of Mattermost Server

**Comment by scottleedavis** [comment]
@hanzei if you are building the Plugin yourself, you will need to do a ‘make clean’ to pull in the latest i18n changes.  ?

**Comment by hanzei** [comment]
Thanks for the help! That fixed it.
