### ISSUE TITLE
Is it possible to make reminders for private channels?

### ISSUE THREAD

**Issue by erdemuysal** [scottleedavis/mattermost-plugin-remind#85]
We use private channels on the company's mattermost server. Is it possible to grant Remindbot these channels?

**Comment by scottleedavis** [comment]
@erdemuysal yes!  

![AE993785-FC02-4CA3-863B-AD4A417A12D3](https://user-images.githubusercontent.com/2914443/56974236-4fe5d300-6b23-11e9-87cd-35494651d80f.png)

**Comment by erdemuysal** [comment]
It was late when I realized I had to add Remindbot to the team and channel 😥
