### ISSUE TITLE
No response from buttons

### ISSUE THREAD

**Issue by momoangel** [scottleedavis/mattermost-plugin-remind#93]
Good Morning!  Thank you for working on this awesome plugin.  I just added it to my dev environment.  the reminders seem to work - but I get no reaction from any of the buttons. :-\  I can click Mark complete, Delete, choose to snooze from the dropdown, and view reminders and nothing seems to happen.  Any ideas?

Thank you!
J

**Comment by scottleedavis** [comment]
Good morning @momoangel !

Could you share your log with DEBUG enabled when you try to click any of the buttons?

**Comment by momoangel** [comment]
Looks like I get a 400 error:

{"level":"error","ts":1557160921.1160393,"caller":"mlog/log.go:172","msg":"Action integration error","path":"/api/v4/posts/rqoq1qoafi8wfb98iy8hf8z98y/actions/xsrwjzifd3nepbfz863s3ej7py","request_id":"redacted","ip_addr":"##.##.##.##","user_id":"redacted","method":"POST","err_where":"DoActionRequest","http_code":400,"err_details":"status=400"}

**Comment by scottleedavis** [comment]
Is the Listen address and siteurl set in server configuration?

What is os is your system running on?

**Comment by momoangel** [comment]
yes - both siteurl and listen address are set.  It's Ubuntu

**Comment by scottleedavis** [comment]
@momoangel could you try the bot-test plugin?
https://github.com/scottleedavis/mattermost-plugin-bot-test/releases/tag/v0.1.1

`/test-button`
`/test-button2`

if test-button fails, uninstall reinstall the plugin.  then try test-button2

please let me know if both, or either, or neither works.  :)

**Comment by momoangel** [comment]
test-button fails, but test-button2 works

Thank you!

**Comment by scottleedavis** [comment]
updated latest version to follow the working button interaction.  Please let me know if it is fixed for you!

https://github.com/scottleedavis/mattermost-plugin-remind/releases/tag/v0.2.3

**Comment by momoangel** [comment]
It works!! :-)  Thank you!
